export default {
    //login
    START_LOGIN: 'START_LOGIN',
    SUCCESS_LOGIN: 'SUCCESS_LOGIN',
    FAILED_LOGIN: 'FAILED_LOGIN',

    //article content
    START_LOAD_ARTICLE: 'START_LOAD_ARTICLE',
    SUCCESS_LOAD_ARTICLE: 'SUCCESS_LOAD_ARTICLE',
    FAILED_LOAD_ARTICLE: 'FAILED_LOAD_ARTICLE',

    //tree data
    START_LOAD_TREE: 'START_LOAD_TREE',
    SUCCESS_LOAD_TREE: 'SUCCESS_LOAD_TREE',
    FAILED_LOAD_TREE: 'FAILED_LOAD_TREE',

    UPDATE_TREE_NODE: 'UPDATE_TREE_NODE',

    //comment
    START_LOAD_COMMENTS: 'START_LOAD_COMMENTS',
    SUCCESS_LOAD_COMMENTS: 'SUCCESS_LOAD_COMMENTS',
    FAILED_LOAD_COMMENTS: 'FAILED_LOAD_COMMENTS',

    START_ADD_COMMENT: 'START_ADD_COMMENT',
    SUCCESS_ADD_COMMENT: 'SUCCESS_ADD_COMMENT',

    DELETE_COMMENT: 'DELETE_COMMENT'
}