export default {
    //login
    START_LOGIN:'START_LOGIN',
    SUCCESS_LOGIN:'SUCCESS_LOGIN',
    FAILED_LOGIN:'FAILED_LOGIN',

    //article content
    START_LOAD_ARTICLE:'START_LOAD_ARTICLE',
    SUCCESS_LOAD_ARTICLE:'SUCCESS_LOAD_ARTICLE',
    FAILED_LOAD_ARTICLE:'FAILED_LOAD_ARTICLE',

    //tree data
    START_LOAD_TREE:'START_LOAD_TREE',
    SUCCESS_LOAD_TREE:'SUCCESS_LOAD_TREE',
    FAILED_LOAD_TREE:'FAILED_LOAD_TREE',

    UPDATE_TREE_NODE:'UPDATE_TREE_NODE'
}